package d.shunyaev.RemoteTrainingTgBot.enums;

import lombok.Getter;

@Getter
public enum Exercises {
    CHEST_1("Жим лёжа на горизонт. скамье", MuscleGroup.CHEST),
    CHEST_2("Жим гантелей на наклонной скамье (верх)", MuscleGroup.CHEST),
    CHEST_3("Жим гантелей на горизонт. скамье", MuscleGroup.CHEST),
    CHEST_4("Жим гантелей на наклонной скамье (верх)", MuscleGroup.CHEST),
    CHEST_5("Разведение гантелей на горизонт. скамье", MuscleGroup.CHEST),
    CHEST_6("Разведение гантелей на наклонной скамье", MuscleGroup.CHEST),
    CHEST_7("Разведение в пек-дек (пек-дек)", MuscleGroup.CHEST),
    CHEST_8("Отжимания на перекладине (поле)", MuscleGroup.CHEST),
    CHEST_9("Отжимания на брусьях (на грудь)", MuscleGroup.CHEST),
    CHEST_10("Пуловер с гантелью", MuscleGroup.CHEST),
    CHEST_11("Пулловер на блоке (клинч-отведение)", MuscleGroup.CHEST),
    CHEST_12("Жим в тренажёре (клиф-жатие)", MuscleGroup.CHEST),
    CHEST_13("Жим гантелей «fly» (разные углы)", MuscleGroup.CHEST),
    CHEST_14("Жим на тренажёре липпинг", MuscleGroup.CHEST),
    CHEST_15("Отжимания с узкой постановкой рук", MuscleGroup.CHEST),
    CHEST_16("Жим штанги в Смита на горизонт. скамье", MuscleGroup.CHEST),
    CHEST_17("Жим штанги в Смита на наклонной скамье", MuscleGroup.CHEST),
    CHEST_18("Разведения рук в кроссовере стоя", MuscleGroup.CHEST),
    CHEST_19("Разведения в кроссовере лёжа (нижняя)", MuscleGroup.CHEST),
    CHEST_20("Жим гантелей с разворотом кисти (hammer)", MuscleGroup.CHEST),
    CHEST_21("Жим гантелей с разворотом кисти (hammer) на наклонной", MuscleGroup.CHEST),
    CHEST_22("Отжимания на кольцах (сумма)", MuscleGroup.CHEST),
    CHEST_23("Жим эспандера стоя (имитация лёжа)", MuscleGroup.CHEST),
    CHEST_24("Разведения рук с эспандером лёжа", MuscleGroup.CHEST),
    CHEST_25("Пуловер со штангой на скамье (широкий)", MuscleGroup.CHEST),

    BACK_1("Тяга штанги в наклоне", MuscleGroup.BACK),
    BACK_2("Тяга блока к груди сидя", MuscleGroup.BACK),
    BACK_3("Тяга верхнего блока за голову", MuscleGroup.BACK),
    BACK_4("Тяга горизонтального блока (сидя)", MuscleGroup.BACK),
    BACK_5("Подтягивания широким хватом", MuscleGroup.BACK),
    BACK_6("Подтягивания узким хватом", MuscleGroup.BACK),
    BACK_7("Тяга в трапеции на блоке", MuscleGroup.BACK),
    BACK_8("Тяга штанги в наклоне", MuscleGroup.BACK),
    BACK_9("Гиперэкстензия", MuscleGroup.BACK),
    BACK_10("Пулловер со штангой/гантелей", MuscleGroup.BACK),
    BACK_11("Тяга гантели одной рукой в наклонке", MuscleGroup.BACK),
    BACK_12("Пуловер на тренажёре", MuscleGroup.BACK),
    BACK_13("Румынская тяга (нижняя часть)", MuscleGroup.BACK),
    BACK_14("Обратная бабочка на тренажёре", MuscleGroup.BACK),
    BACK_15("Тяга Т-штанги в наклоне", MuscleGroup.BACK),
    BACK_16("Тяга штанги к подбородку стоя", MuscleGroup.BACK),
    BACK_17("Тяга верхнего блока узким хватом", MuscleGroup.BACK),
    BACK_18("Подтягивания нейтральным хватом", MuscleGroup.BACK),
    BACK_19("Тяга штанги в наклоне с гантелями", MuscleGroup.BACK),
    BACK_20("разведение рук в стороны в наклоне", MuscleGroup.BACK),
    BACK_21("Тяга блока к животу сидя", MuscleGroup.BACK),
    BACK_22("Гиперэкстензия с отягощением", MuscleGroup.BACK),
    BACK_23("Ласточка (статическое)", MuscleGroup.BACK),
    BACK_24("Тяга горизонтального блока одной рукой", MuscleGroup.BACK),
    BACK_25("Подтягивания с весом", MuscleGroup.BACK),
    BACK_26("Тяга верхнего блока с V-образной рукоятью", MuscleGroup.BACK),
    BACK_27("Обратные гиперэкстензии", MuscleGroup.BACK),
    BACK_28("Тяга штанги в раме (Power Rack)", MuscleGroup.BACK),
    BACK_29("Отжимания на брусьях с отягощением", MuscleGroup.BACK),
    BACK_30("Разгибание спины с блином", MuscleGroup.BACK),
    BACK_31("Тяга эспандера к груди стоя", MuscleGroup.BACK),
    BACK_32("Подтягивания на перекладине с обратным хватом", MuscleGroup.BACK),

    LEGS_1("Присед со штангой на плечах", MuscleGroup.LEGS),
    LEGS_2("Присед с гантелями", MuscleGroup.LEGS),
    LEGS_3("Жим штанги ногами в тренажёре", MuscleGroup.LEGS),
    LEGS_4("Выпады с гантелями/штангой", MuscleGroup.LEGS),
    LEGS_5("Становая тяга на прямых ногах", MuscleGroup.LEGS),
    LEGS_6("Становая тяга sumo", MuscleGroup.LEGS),
    LEGS_7("Разгибание ног в тренажёре", MuscleGroup.LEGS),
    LEGS_8("Сгибание ног в тренажёре лёжа", MuscleGroup.LEGS),
    LEGS_9("Подъёмы на носки стоя", MuscleGroup.LEGS),
    LEGS_10("Подъёмы на носки сидя", MuscleGroup.LEGS),
    LEGS_11("Жим платформы", MuscleGroup.LEGS),
    LEGS_12("Выпады на месте с шагом", MuscleGroup.LEGS),
    LEGS_13("Передний присед", MuscleGroup.LEGS),
    LEGS_14("Болгарские сплит-присед", MuscleGroup.LEGS),
    LEGS_15("Мостик/Glute bridge", MuscleGroup.LEGS),
    LEGS_16("Махи ногами в стороны и назад", MuscleGroup.LEGS),
    LEGS_17("Приседания в Гакк-машине", MuscleGroup.LEGS),
    LEGS_18("Фронтальные приседания в Смита", MuscleGroup.LEGS),
    LEGS_19("Румынская тяга", MuscleGroup.LEGS),
    LEGS_20("Сгибание ног стоя с гантелями", MuscleGroup.LEGS),
    LEGS_21("Подъём на ступеньку с весом", MuscleGroup.LEGS),
    LEGS_22("Жим ногами узко", MuscleGroup.LEGS),
    LEGS_23("Жим ногами широко", MuscleGroup.LEGS),
    LEGS_24("Отведение ноги назад в тренажёре", MuscleGroup.LEGS),
    LEGS_25("Приседания с паузой", MuscleGroup.LEGS),
    LEGS_26("Выпады с поворотом корпуса", MuscleGroup.LEGS),
    LEGS_27("Подъёмы на носки с лентой", MuscleGroup.LEGS),
    LEGS_28("Сгибание ног сидя", MuscleGroup.LEGS),
    LEGS_29("Прыжки на ящик/платформу", MuscleGroup.LEGS),
    LEGS_30("Обратные выпады с гантелями", MuscleGroup.LEGS),
    LEGS_31("Приседания пистолетик", MuscleGroup.LEGS),
    LEGS_32("Махи ногой в кроссовере", MuscleGroup.LEGS),
    LEGS_33("Разгибание голени сидя", MuscleGroup.LEGS),
    LEGS_34("Скручивания голени эспандером", MuscleGroup.LEGS),
    LEGS_35("Шаги в сторону с гантелями", MuscleGroup.LEGS),
    LEGS_36("Подъёмы на носки на одной ноге", MuscleGroup.LEGS),
    LEGS_37("Тяга ногой в тренажёре", MuscleGroup.LEGS),
    LEGS_38("Приседания с подъёмом на носки", MuscleGroup.LEGS),
    LEGS_39("Зашагивания на платформу с гантелями", MuscleGroup.LEGS),
    LEGS_40("Статический мостик", MuscleGroup.LEGS),

    TRICEPS_1("Разгибания рук на блочном тренажёре стоя", MuscleGroup.TRICEPS),
    TRICEPS_2("Разгибания на верхнем блоке", MuscleGroup.TRICEPS),
    TRICEPS_3("Французский жим лёжа", MuscleGroup.TRICEPS),
    TRICEPS_4("Французский жим гантелей сидя", MuscleGroup.TRICEPS),
    TRICEPS_5("Отжимания узким хватом", MuscleGroup.TRICEPS),
    TRICEPS_6("Отжимания на брусьях с акцентом на трицепс", MuscleGroup.TRICEPS),
    TRICEPS_7("Разгибания одной гантели over head", MuscleGroup.TRICEPS),
    TRICEPS_8("Кикбеки с гантелями", MuscleGroup.TRICEPS),
    TRICEPS_9("Раменные отжимания на трицепс", MuscleGroup.TRICEPS),
    TRICEPS_10("Разгибания на тренажёре трицепсовая катапульта", MuscleGroup.TRICEPS),
    TRICEPS_11("Скотч-трипс на блоке", MuscleGroup.TRICEPS),
    TRICEPS_12("Разгибания рук гантелями из-за головы сидя", MuscleGroup.TRICEPS),
    TRICEPS_13("Жим гантелей узким хватом на наклонной скамье", MuscleGroup.TRICEPS),
    TRICEPS_14("Разгибания рук в локтевом суставе с гантелями", MuscleGroup.TRICEPS),
    TRICEPS_15("Французский жим с гантелями лёжа", MuscleGroup.TRICEPS),
    TRICEPS_16("Разгибания на нижнем блоке с канатом", MuscleGroup.TRICEPS),
    TRICEPS_17("Отжимания на скамье узким хватом", MuscleGroup.TRICEPS),
    TRICEPS_18("Жим штанги узким хватом на горизонтальной скамье", MuscleGroup.TRICEPS),
    TRICEPS_19("Разгибания одной руки в кроссовере", MuscleGroup.TRICEPS),
    TRICEPS_20("Разгибания рук с резиной стоя", MuscleGroup.TRICEPS),
    TRICEPS_21("Французский жим EZ-штангой", MuscleGroup.TRICEPS),
    TRICEPS_22("Разгибания на блоке прямой рукоятью сидя", MuscleGroup.TRICEPS),
    TRICEPS_23("Отжимания на параллельных брусьях с отягощением", MuscleGroup.TRICEPS),
    TRICEPS_24("Разгибания рук гантелью в упоре на скамье", MuscleGroup.TRICEPS),
    TRICEPS_25("Жим платформы ногами для трицепса", MuscleGroup.TRICEPS),
    TRICEPS_26("Разгибания рук лентой-резинкой", MuscleGroup.TRICEPS),
    TRICEPS_27("Французский жим гантелей лёжа с разворотом кистей", MuscleGroup.TRICEPS),
    TRICEPS_28("Разгибания на блоке с канатом", MuscleGroup.TRICEPS),
    TRICEPS_29("Отжимания на кольцах с узким хватом", MuscleGroup.TRICEPS),
    TRICEPS_30("Разгибания рук гантелями стоя", MuscleGroup.TRICEPS),

    BICEPS_1("Подъём штанги стоя (прямой хват)", MuscleGroup.BICEPS),
    BICEPS_2("Подъём гантелей стоя поочерёдно", MuscleGroup.BICEPS),
    BICEPS_3("Молотковый хват (hammer curl)", MuscleGroup.BICEPS),
    BICEPS_4("Концентрационный подъём сидя", MuscleGroup.BICEPS),
    BICEPS_5("Подъёмы на скамье Скотта", MuscleGroup.BICEPS),
    BICEPS_6("Подъёмы на кроссовере (low pulley)", MuscleGroup.BICEPS),
    BICEPS_7("Подъёмы лодочкой на блоке", MuscleGroup.BICEPS),
    BICEPS_8("Подъём на блоке узким хватом", MuscleGroup.BICEPS),
    BICEPS_9("Кроссовер‑подъёмы на бицепс", MuscleGroup.BICEPS),
    BICEPS_10("Подъём штанги обратным хватом стоя", MuscleGroup.BICEPS),
    BICEPS_11("Подъём гантелей «молотки» сидя", MuscleGroup.BICEPS),
    BICEPS_12("Подъёмы EZ‑штанги на скамье Скотта", MuscleGroup.BICEPS),
    BICEPS_13("Подъёмы с канатной рукоятью", MuscleGroup.BICEPS),
    BICEPS_14("Подъёмы гантелей на наклонной скамье", MuscleGroup.BICEPS),
    BICEPS_15("Подъёмы EZ‑штанги стоя", MuscleGroup.BICEPS),
    BICEPS_16("Подъёмы одной гантели на скамье", MuscleGroup.BICEPS),
    BICEPS_17("Подъёмы с резиновым эспандером", MuscleGroup.BICEPS),
    BICEPS_18("Подъёмы на нижнем блоке с рукоятью", MuscleGroup.BICEPS),
    BICEPS_19("Подъёмы гантелей «сумо» (широкая)", MuscleGroup.BICEPS),
    BICEPS_20("Подъёмы штанги в Смита (ограничение)", MuscleGroup.BICEPS),
    BICEPS_21("Подъёмы гантелей «частота»", MuscleGroup.BICEPS),
    BICEPS_22("Подъёмы на блочном тренажёре с V‑образной рукоятью", MuscleGroup.BICEPS),
    BICEPS_23("Подтягивания обратным хватом с отягощением", MuscleGroup.BICEPS),
    BICEPS_24("Подъёмы гантелей с супи­naцией", MuscleGroup.BICEPS),
    BICEPS_25("Подъёмы на тренажёре «бицепс‑машина»", MuscleGroup.BICEPS),
    BICEPS_26("Подъёмы с лентой-резинкой в Stand", MuscleGroup.BICEPS),
    BICEPS_27("Подъёмы штанги узким хватом в упоре", MuscleGroup.BICEPS),
    BICEPS_28("Подъёмы гантелей сидя у бедра", MuscleGroup.BICEPS),
    BICEPS_29("Подъёмы на кроссовере с канатом", MuscleGroup.BICEPS),
    BICEPS_30("Подъёмы с гирей", MuscleGroup.BICEPS),

    SHOULDERS_1("Жим штанги стоя (армейский)", MuscleGroup.SHOULDERS),
    SHOULDERS_2("Жим гантелей сидя/стоя", MuscleGroup.SHOULDERS),
    SHOULDERS_3("Подъёмы гантелей в стороны", MuscleGroup.SHOULDERS),
    SHOULDERS_4("Подъёмы гантелей перед собой", MuscleGroup.SHOULDERS),
    SHOULDERS_5("Тяги штанги к подбородку (upright)", MuscleGroup.SHOULDERS),
    SHOULDERS_6("Махи задние с гантелями в наклоне", MuscleGroup.SHOULDERS),
    SHOULDERS_7("Разведения на пек-дек (задняя дельта)", MuscleGroup.SHOULDERS),
    SHOULDERS_8("Армейский жим на блоках/кроссовере", MuscleGroup.SHOULDERS),
    SHOULDERS_9("Тяги за голову на верхнем блоке", MuscleGroup.SHOULDERS),
    SHOULDERS_10("Arnold press", MuscleGroup.SHOULDERS),
    SHOULDERS_11("Подъёмы гантелей в горизонтальном", MuscleGroup.SHOULDERS),
    SHOULDERS_12("Жим Смита стоя (армейский)", MuscleGroup.SHOULDERS),
    SHOULDERS_13("Разведения гантелей в наклоне (задние)", MuscleGroup.SHOULDERS),
    SHOULDERS_14("Подъёмы штанги перед собой (фронт)", MuscleGroup.SHOULDERS),
    SHOULDERS_15("Разведение рук в кроссовере (задняя)", MuscleGroup.SHOULDERS),
    SHOULDERS_16("Жим гантелей на наклонной (передние)", MuscleGroup.SHOULDERS),
    SHOULDERS_17("Подъёмы на блоке с канатом вперёд", MuscleGroup.SHOULDERS),
    SHOULDERS_18("Махи в стороны сидя (пояснич. сниз.)", MuscleGroup.SHOULDERS),
    SHOULDERS_19("Тяги гантелей к подбородку в наклоне", MuscleGroup.SHOULDERS),
    SHOULDERS_20("Бабочка в тренажёре (для дельт)", MuscleGroup.SHOULDERS),
    SHOULDERS_21("Подъёмы EZ‑штанги перед собой", MuscleGroup.SHOULDERS),
    SHOULDERS_22("Жимы на тренажёре для плеч", MuscleGroup.SHOULDERS),
    SHOULDERS_23("Махи в кроссовере (зад. дельты)", MuscleGroup.SHOULDERS),
    SHOULDERS_24("Подъёмы гантелей молотками", MuscleGroup.SHOULDERS),
    SHOULDERS_25("Тяги лентой к подбородку", MuscleGroup.SHOULDERS),
    SHOULDERS_26("Разведения с гантелями на скамье", MuscleGroup.SHOULDERS),
    SHOULDERS_27("Жим гантелей двумя руками вверх", MuscleGroup.SHOULDERS),
    SHOULDERS_28("Подъёмы гири перед собой", MuscleGroup.SHOULDERS),
    SHOULDERS_29("Разведения в кроссовере нижнего блока", MuscleGroup.SHOULDERS),
    SHOULDERS_30("Подъёмы штанги на Смита с узким хватом", MuscleGroup.SHOULDERS),

    CARDIO_1("Бег на дорожке", MuscleGroup.CARDIO),
    CARDIO_2("Эллипсоид", MuscleGroup.CARDIO),
    CARDIO_3("Велотренажёр", MuscleGroup.CARDIO),
    CARDIO_4("Степпер", MuscleGroup.CARDIO),
    CARDIO_5("Скакалка", MuscleGroup.CARDIO),
    CARDIO_6("Интервальные кардио-программы", MuscleGroup.CARDIO),
    CARDIO_7("Круговая тренировка", MuscleGroup.CARDIO),
    CARDIO_8("Беговая дорожка с наклоном", MuscleGroup.CARDIO),
    CARDIO_9("Орбитрек", MuscleGroup.CARDIO),
    CARDIO_10("Гребной тренажёр", MuscleGroup.CARDIO),
    CARDIO_11("Плавание", MuscleGroup.CARDIO),
    CARDIO_12("Бег на улице", MuscleGroup.CARDIO),
    CARDIO_13("Ходьба на свежем воздухе", MuscleGroup.CARDIO),
    CARDIO_14("Скандинавская ходьба", MuscleGroup.CARDIO),
    CARDIO_15("Интервальный бег (HIIT)", MuscleGroup.CARDIO),
    CARDIO_16("Степ-аэробика", MuscleGroup.CARDIO),
    CARDIO_17("Прыжки на месте (Jumping Jacks)", MuscleGroup.CARDIO),
    CARDIO_18("Бег с высоким подъёмом колен", MuscleGroup.CARDIO),
    CARDIO_19("Приседания с выпрыгиванием", MuscleGroup.CARDIO),
    CARDIO_20("Берпи", MuscleGroup.CARDIO),
    CARDIO_21("Велосипед на улице/вело-", MuscleGroup.CARDIO),
    CARDIO_22("Ходьба по лестнице", MuscleGroup.CARDIO),
    CARDIO_23("Низкоударные берпи", MuscleGroup.CARDIO),
    CARDIO_24("Бег из стороны в сторону", MuscleGroup.CARDIO),
    CARDIO_25("Плиометр боковые выпады", MuscleGroup.CARDIO),
    CARDIO_26("Прыжки в планке с разведения ног", MuscleGroup.CARDIO),
    CARDIO_27("Горизонтальный бег (упор)", MuscleGroup.CARDIO),
    CARDIO_28("Прыжки со скакалкой", MuscleGroup.CARDIO),
    CARDIO_29("Кардио‑комплекс с резинкой", MuscleGroup.CARDIO),
    CARDIO_30("Кроссфит с кардио элементами", MuscleGroup.CARDIO);

    private final String description;
    private final MuscleGroup muscleGroup;

    Exercises(String description, MuscleGroup muscleGroup) {
        this.description = description;
        this.muscleGroup = muscleGroup;
    }
}